name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # only trigger on version-like tags

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to check full commit history

      - name: Ensure tag is on main
        run: |
          TAG_COMMIT=$(git rev-parse HEAD)
          echo "Tag points to commit: $TAG_COMMIT"
          git fetch origin main
          if git merge-base --is-ancestor $TAG_COMMIT origin/main; then
            echo "Tag is on main branch ✅"
          else
            echo "Tag is NOT on main branch ❌"
            exit 1
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_RELEASE_MAKER_TOKEN }}